#!/usr/bin/env python3
"""The Master's gun overlay (docs/master_textured_spec.md step 6f): the
spec the 6502's gun_draw reproduces byte for byte.

art/gun/PISGA0.txt is DOOM's idle pistol redrawn as Mode 2 pixel art: 24 x
25, each pixel one Mode 2 pixel by two lines (a square fat pixel, like a
wall texel), ' ' transparent. DOOM draws PISGA0 at (126, 106) on its 320 x
200 screen over a 168-line view; scaled 0.4 that is pixel 50, row 43 of our
128 x 68 view, so the grid's bottom row sits on line 135, the panel's edge.

Drawn into the back buffer after each frame, before the flip, as masked
whole bytes: a byte keeps the screen's bits of its transparent pixel(s)
(mask) and ORs in the art (data). The table, per grid row, is
    .byte line, first byte column, count, then count x (mask, data)
and $FF ends it. `python3 master_gun.py` writes it to src/master/mgun_tab.s.
"""
import os

import master_assets as M

ROOT = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(ROOT, 'art', 'gun', 'PISGA0.txt')
TAB = os.path.join(ROOT, 'src', 'master', 'mgun_tab.s')
CH = '.rgybmcw'
X0 = 50                                 # the grid's first pixel (even: a byte edge)
LINE0 = 136 - 2 * 25                    # its first line (86)


def grid():
    rows = [l.rstrip('\n') for l in open(ART) if not l.startswith('#')]
    rows = [r for r in rows if r.strip()]
    w = max(len(r) for r in rows)
    return [[None if ch == ' ' else CH.index(ch) for ch in r.ljust(w)] for r in rows]


def table():
    """[(line, byte column, [(mask, data), ...]), ...] for the grid's rows."""
    out = []
    for r, row in enumerate(grid()):
        cells = []
        for k in range(0, len(row), 2):
            l, rt = row[k], row[k + 1] if k + 1 < len(row) else None
            mask = (0xAA if l is None else 0) | (0x55 if rt is None else 0)
            data = M.mode2_byte((l or 0, rt or 0)) & ~mask & 0xFF
            cells.append((X0 // 2 + k // 2, mask, data))
        cells = [c for c in cells if c[1] != 0xFF]
        if cells:
            first = cells[0][0]
            assert [c[0] for c in cells] == list(range(first, first + len(cells))), 'a gap in a gun row'
            out.append((LINE0 + 2 * r, first, [(m, d) for _, m, d in cells]))
    return out


def apply(fb):
    """The buffer with the gun drawn on it (both lines of each grid row)."""
    fb = bytearray(fb)
    for line, x, cells in table():
        for y in (line, line + 1):
            for j, (m, d) in enumerate(cells):
                a = (y >> 3) * 512 + (x + j) * 8 + (y & 7)
                fb[a] = (fb[a] & m) | d
    return bytes(fb)


def source():
    s = ['; GENERATED by master_gun.py from art/gun/PISGA0.txt -- do not edit',
         '; per grid row: line, first byte column, count, count x (mask, data)',
         'gun_tab:']
    for line, x, cells in table():
        s.append(f'   .byte {line}, {x}, {len(cells)}')
        s.append('   .byte ' + ', '.join(f'${m:02X}, ${d:02X}' for m, d in cells))
    s.append('   .byte $FF')
    return '\n'.join(s) + '\n'


if __name__ == '__main__':
    open(TAB, 'w').write(source())
    t = table()
    print(f'{TAB}: {len(t)} rows, {sum(len(c) for _, _, c in t)} bytes a line, '
          f'{sum(3 + 2 * len(c) for _, _, c in t) + 1} B of table')
