#!/usr/bin/env python3
"""The Master's gun overlay (docs/master_textured_spec.md step 6f): the
spec the 6502's gun_draw reproduces byte for byte.

art/gun/PISGA0.txt is DOOM's idle pistol redrawn as Mode 2 pixel art: 24 x
50, each pixel one Mode 2 pixel by ONE line (full vertical resolution: the
first cut at two lines a pixel was too blocky to read as a hand), ' '
transparent. DOOM draws PISGA0 at (126, 106) on its 320 x 200 screen over a
168-line view; scaled 0.4 x 0.81 that is pixel 50, line 86 of our 128 x 136
view, so the grid's bottom row is line 135, the panel's edge.

Drawn into the back buffer after each frame, before the flip, as whole
bytes: a byte keeps the screen's bits of its transparent pixel(s) (mask) and
ORs in the art (data). Most of the gun's bytes have no transparent pixel, so
they are simply written. `python3 master_gun.py` compiles the table into
straight-line code, one copy per screen buffer (absolute addresses), in
src/master/mgun_tab.s: the opaque bytes sorted by value, each value loaded
once and then stored (LDA #d, STA abs, STA abs ...), then the edge bytes
read-modify-written (LDA abs, AND #m, [ORA #d,] STA abs).
"""
import os

import master_assets as M

ROOT = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(ROOT, 'art', 'gun', 'PISGA0.txt')
TAB = os.path.join(ROOT, 'src', 'master', 'mgun_tab.s')
CH = '.rgybmcw'
X0 = 50                                 # the grid's first pixel (even: a byte edge)



def grid():
    rows = [l.rstrip('\n') for l in open(ART) if not l.startswith('#')]
    rows = [r for r in rows if r.strip()]
    w = max(len(r) for r in rows)
    return [[None if ch == ' ' else CH.index(ch) for ch in r.ljust(w)] for r in rows]


def table():
    """[(line, byte column, [(mask, data), ...]), ...] for the grid's rows."""
    out = []
    rows = grid()
    line0 = 136 - len(rows)                     # the bottom row on line 135
    for r, row in enumerate(rows):
        cells = []
        for k in range(0, len(row), 2):
            l, rt = row[k], row[k + 1] if k + 1 < len(row) else None
            mask = (0xAA if l is None else 0) | (0x55 if rt is None else 0)
            data = M.mode2_byte((l or 0, rt or 0)) & ~mask & 0xFF
            cells.append((X0 // 2 + k // 2, mask, data))
        cells = [c for c in cells if c[1] != 0xFF]
        if cells:
            first = cells[0][0]
            assert [c[0] for c in cells] == list(range(first, first + len(cells))), 'a gap in a gun row'
            out.append((line0 + r, first, [(m, d) for _, m, d in cells]))
    return out


def apply(fb):
    """The buffer with the gun drawn on it."""
    fb = bytearray(fb)
    for y, x, cells in table():
        for j, (m, d) in enumerate(cells):
            a = (y >> 3) * 512 + (x + j) * 8 + (y & 7)
            fb[a] = (fb[a] & m) | d
    return bytes(fb)


def cells():
    """[(buffer offset, mask, data), ...], every byte the gun touches."""
    return [((y >> 3) * 512 + (x + j) * 8 + (y & 7), m, d)
            for y, x, row in table() for j, (m, d) in enumerate(row)]


def source():
    s = ['; GENERATED by master_gun.py from art/gun/PISGA0.txt -- do not edit',
         '; the gun overlay, one routine per screen buffer (ACCCON X set)']
    cs = cells()
    opaque = sorted((d, a) for a, m, d in cs if m == 0)
    edge = sorted((a, m, d) for a, m, d in cs if m != 0)
    for k, base in enumerate(('MSCREEN0', 'MSCREEN1')):
        s.append(f'gun_b{k}:')
        last = None
        for d, a in opaque:
            if d != last:
                s.append(f'   LDA #${d:02X}')
                last = d
            s.append(f'   STA {base}+${a:04X}')
        for a, m, d in edge:
            s.append(f'   LDA {base}+${a:04X}')
            s.append(f'   AND #${m:02X}')
            if d:
                s.append(f'   ORA #${d:02X}')
            s.append(f'   STA {base}+${a:04X}')
        s.append('   RTS')
    return '\n'.join(s) + '\n'


if __name__ == '__main__':
    open(TAB, 'w').write(source())
    cs = cells()
    n0 = sum(1 for _, m, _ in cs if m == 0)
    print(f'{TAB}: {len(cs)} bytes, {n0} opaque, {len(cs) - n0} edge')
