#!/usr/bin/env python3
"""The Tube Master host drawer's build and py65 rig (docs/tube_master.md
step 3). src/tube/hdraw.s draws an encoded display list (tube_dl.encode)
read from the Tube's register 1; this assembles it with its tables and runs
it on a 64K py65 memory that models what it touches: the Tube's register
1 (status $FEE0, data $FEE1) as a FIFO the list sits in, ROMSEL ($FE30)
over the sideways window, and the screen buffer at SCREEN.

The tables come from the Master build's own assets: the textures' banks,
pages and row offsets (master_assets' manifest), a logical-column to
stored-column index per texture, the flats' banks and pages; banks 5 and 6
are master_walls.rig_images() -- the bytes the Master disc ships.
"""
import os
import subprocess

import master_assets as M
import master_walls as MW
import tube_dl

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, 'build', 'tube')
SRC = os.path.join(ROOT, 'src', 'tube')
SCREEN = 0x3000                          # the view's 17 character rows
VIEW_BYTES = 17 * 512
TRAMP = 0x0200


def tables(R):
    """hdraw_tab.inc for DLRef R's assets."""
    man = R.T.A.man
    rows = lambda name, data: [f'{name}:'] + ['\t.byte ' + ','.join(f'${v & 0xFF:02X}' for v in data[i:i + 16])
                                              for i in range(0, len(data), 16)]
    tex = sorted(man['textures'], key=lambda t: t['id'])
    assert [t['id'] for t in tex] == list(range(len(tex)))
    ix, ixo = [], []
    for t in tex:
        ixo.append(len(ix))
        ix += t['index']
    flats = sorted(man['flats'], key=lambda f: f['id'])
    s = ['; GENERATED by tube_host.py -- do not edit',
         f'SCREEN = ${SCREEN:04X}', f'SKY_BYTE = ${M.SKY_BYTE:02X}', f'PAIR_Y = ${tube_dl.PAIR_Y:02X}',
         '.macro TABLES']
    s += rows('tx_bank', [t['bank'] for t in tex])
    s += rows('tx_ph', [t['ptr'] >> 8 for t in tex])
    s += rows('tx_ro', [t['rowoff'] for t in tex])
    s += rows('tx_rm', [(R.W.tparams[t['id']]['th'] - 1) * 8 for t in tex])
    s += ['tx_ixl:'] + [f'\t.byte <(tx_ix + {o})' for o in ixo]
    s += ['tx_ixh:'] + [f'\t.byte >(tx_ix + {o})' for o in ixo]
    s += rows('tx_ix', ix)
    s += rows('fl_bank', [f['bank'] for f in flats])
    s += rows('fl_page', [f['ptr'] >> 8 for f in flats])
    s += ['.align 256'] + rows('lsr4', [u >> 4 for u in range(256)])
    s += rows('flip', list(M.FLIP))
    s.append('.endmacro')
    return '\n'.join(s) + '\n'


_MT = None


def master_tables(L):
    """The Master host drawer's tables (src/tube/hdraw.s, MASTER), seeded by
    symbol L (name -> address): [(address, bytes)]. The same tables as
    tables() makes for the flat drawer, from the Master build's assets."""
    global _MT
    if _MT is None:
        import textured_ref
        T = textured_ref.TexturedRef()
        _MT = T.A.man, MW.Walls(T.dw, T.tex, T.A.man).tparams
    man, tparams = _MT
    tex = sorted(man['textures'], key=lambda t: t['id'])
    assert [t['id'] for t in tex] == list(range(len(tex))) and len(tex) <= 32
    flats = sorted(man['flats'], key=lambda f: f['id'])
    assert len(flats) <= 32
    ix, ixo = [], []
    for t in tex:
        ixo.append(len(ix))
        ix += t['index']
    assert len(ix) <= 896, 'the column indexes overrun tx_ix'
    base = L('tx_ix')
    return [(L('tx_bank'), bytes(t['bank'] for t in tex)),
            (L('tx_ph'), bytes(t['ptr'] >> 8 for t in tex)),
            (L('tx_ro'), bytes(t['rowoff'] for t in tex)),
            (L('tx_rm'), bytes((tparams[t['id']]['th'] - 1) * 8 for t in tex)),
            (L('tx_ixl'), bytes((base + o) & 0xFF for o in ixo)),
            (L('tx_ixh'), bytes((base + o) >> 8 for o in ixo)),
            (L('tx_ix'), bytes(ix)),
            (L('fl_bank'), bytes(f['bank'] for f in flats)),
            (L('fl_page'), bytes(f['ptr'] >> 8 for f in flats))]


def build(R):
    """(code bytes, labels)."""
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, 'hdraw_tab.inc'), 'w').write(tables(R))
    obj, binp, lab = (os.path.join(OUT, 'hdraw' + x) for x in ('.o', '.bin', '.lab'))
    subprocess.run(['ca65', '-g', '--cpu', '65C02', '-I', OUT, '-I', SRC,
                    os.path.join(SRC, 'hdraw.s'), '-o', obj], check=True)
    subprocess.run(['ld65', '-C', os.path.join(SRC, 'hdraw.cfg'), obj, '-o', binp, '-Ln', lab],
                   check=True)
    labels = {}
    for line in open(lab):
        a, n = line.split()[1:3]
        labels[n.lstrip('.')] = int(a, 16)
    return open(binp, 'rb').read(), labels


class Mem(list):
    """64K: the Tube's register 1 (a FIFO holding the list), ROMSEL over
    $8000-$BFFF."""

    def __init__(self, banks):
        super().__init__([0] * 0x10000)
        self.banks, self.rom = banks, None
        self.fifo, self.fp = b'', 0

    def __getitem__(self, a):
        if 0x8000 <= a < 0xC000:
            return self.banks[self.rom][a - 0x8000]
        if a == 0xFEE0:
            return 0x80 if self.fp < len(self.fifo) else 0
        if a == 0xFEE1:
            self.fp += 1
            return self.fifo[self.fp - 1]
        return list.__getitem__(self, a)

    def __setitem__(self, a, v):
        if a == 0xFE30:
            self.rom = v & 15
        elif 0x8000 <= a < 0xC000:
            raise RuntimeError(f'write to the sideways window ${a:04X}')
        else:
            list.__setitem__(self, a, v)


class Host:
    def __init__(self, R):
        from py65.devices.mpu65c02 import MPU
        code, self.lab = build(R)
        rig = MW.rig_images()
        self.mem = Mem({5: rig['b5'], 6: rig['b6']})
        for i, b in enumerate(code):
            list.__setitem__(self.mem, 0x1000 + i, b)
        self.mpu = MPU(memory=self.mem)

    def draw(self, enc):
        """Run hd_frame over the encoded list: (view bytes, cycles)."""
        m = self.mem
        for a in range(SCREEN, SCREEN + VIEW_BYTES):
            list.__setitem__(m, a, 0)
        m.fifo, m.fp = enc, 0
        e = self.lab['hd_frame']
        for i, b in enumerate((0x20, e & 0xFF, e >> 8)):     # JSR hd_frame
            list.__setitem__(m, TRAMP + i, b)
        mpu = self.mpu
        mpu.pc, mpu.sp = TRAMP, 0xFF
        c0 = mpu.processorCycles
        while mpu.pc != TRAMP + 3:
            mpu.step()
            if mpu.processorCycles - c0 > 5_000_000:
                raise RuntimeError(f'runaway at ${mpu.pc:04X} after {m.fp} of {len(enc)} list bytes')
        assert m.fp == len(enc), f'read {m.fp} of {len(enc)} list bytes'
        return bytes(list.__getitem__(m, slice(SCREEN, SCREEN + VIEW_BYTES))), mpu.processorCycles - c0
