
; ============================================================================
; Animated sectors (doors / lifts) — 6502 runtime.
;
; Mirrors the python prototype's two-level design (anim_sectors.py):
;   LOGICAL heights advance every frame in anim_tick (per-mover state
;   machine over a 3-byte block: pos 8.8 prescaled + packed state/timer).
;   APPLIED heights (the bytes the renderer reads) update lazily: the
;   render_subsector hook (anim_ss_hook, SMC like the vrcache/bca hooks)
;   consults a per-subsector mover bitmask and patches a dirty mover the
;   first time a frame visits any subsector containing one of its segs.
;   An invisible mover's stale bytes are never read, so lazy == eager.
;
; A patch writes, per mover (table-driven; tables generated at pack time
; by anim_sectors.gen_6502_tables and poked by the harness/disc build):
;   HEIGHT bytes — n_fhch u16 addrs: the per-subsector front-height pages
;     for the mover's own sector, the seg headers' +10/+11 back pair for
;     segs facing it (the separate FHCH stream was retired 2026-07-11 — the
;     'fhch' naming in the tables survives as history), value = pos_hi
;   seg-header FLAG bytes — SOLID/NEEDBT/NEEDBB re-derived from the
;     (patched) height quad
; Both live in bank L0 banked / $6C00 flat, so the workers run paged.
;
; Segments (ALL code in the one CODE region banked; flat: ANIMH+ANIML0
; in the ACOLD island $E740, ANIML2 in CODE — see engine_flat.cfg):
; ANIMH = resident hub (pages banks, walks dirty&visible bits);
; ANIML0 = header height+flags patch worker (runs with BANK_L0 paged);
; ANIML2 = tick + init (runs with BANK_L2 paged: the CFG table lives in
; the L2 window at $BA00).
; ============================================================================

; --- table/data addresses (contents generated by anim_sectors.py) ---
; ANIM_SSMASK is the SIXTH per-subsector plane (Eben, 2026-08-19): the
; hub is entered WALK-paged (see the subsector prologue), so the banked
; mask reads IN PLACE from the bank-B page the disc ships — the old
; $1100 main copy and anim_init's page copy-down are DELETED, and $1100
; is free in BOTH builds (flat reads its own shipped page too).
ANIM_TABL0  = BANKA_ORG + $3A00         ; bank A: 6 u16 ptrs -> per-mover blocks (moved $BE90->$BA00 by the 2026-09-02 top-of-A free of 512 B)
ANIM_CFG    = BANKB_ORG + $3300         ; bank B: 12 B per mover (bounds/speed/waits)
ANIM_SSMASK = BANKB_ORG + $3400         ; bank B (=WALK): read by the hub under
                                        ; the bank it already holds — zero
                                        ; paging; the +$34DD-$34FF tail is free
; CFG record layout (12 B/mover, anim_sectors.gen_6502_tables; heights are
; prescaled 8.8 fixed point — hi byte = the packer's prescaled s8 height):
;   +0  min88  (s16: endpoint "A" — doors: closed, lifts: bottom)
;   +2  max88  (s16: endpoint "B" — doors: open,   lifts: top)
;   +4  speed88 (u16, per FIELD — anim_tick scales by ANIM_FIELDS)
;   +6  wait_at_A, +7 wait_at_B (4-FIELD units, <= 63 for the packed timer)
;   +8  start88, +10 packed start state/timer, +11 pad
; Mover bit/index m = index in sorted(ANIM_SECTORS) everywhere (SSMASK bits,
; TABL0 pointer slots, CFG stride 12, ANIM_WS stride 3, DIRTY bits).

; --- state (unbanked; ships as LOW zeros, anim_init seeds it) ---
ANIM_FIELDS = $0D68                     ; PAL fields this frame consumed —
                                        ; the DRIVER stores its mv_frame /
                                        ; mask-drain count here before the
                                        ; tick (2026-08-25); 0 (harness, no
                                        ; driver) ticks as 1 field. Byte
                                        ; below the anim block: the old
                                        ; VRCACHE senior-plane tail, free since
                                        ; n_verts <= 480.
ANIM_ENABLE = $0D69                     ; scalars block: $05xx -> $1Dxx (sqr
ANIM_DIRTY  = $0D6A                     ; swap) -> $19xx (2026-08-19 window
ANIM_WS     = $0D6B                     ; slide); same page offsets.
ANIM_TPRE   = $0D7D                     ; wait prescaler residue (2026-08-25
                                        ; field-scaled: accumulates FIELDS,
                                        ; the whole /4 steps are consumed
                                        ; into at_wsteps each tick, the
                                        ; residue 0-3 stays). Waits tick per
                                        ; 4 FIELDS so the 6-bit timer spans
                                        ; multi-second holds; ships as LOW
                                        ; zeros
                                        ; per mover: pos_lo, pos_hi, state/timer
                                        ;   state = bits 7-6 (0 wait@A, 1 A->B,
                                        ;   2 wait@B, 3 B->A), timer = bits 5-0

; --- zp scratch (frame-scoped; free per zpcheck) ---
; (zp_anim_p/zp_anim_w/ANIM_VAL/ANIM_CUR moved to zp.inc 2026-07-10 —
; registered at $5D/$5F/$27/$29; they were unregistered squatters at
; $EB-$EE/$F0/$F1, which now belong to the free top block.)

; ============================================================================
; Resident hub — anim_ss_hook (in subsector.s) is SMC-patched here by
; anim_init. Entry: bank WALK paged (the hook moved to the FRONT of the
; prologue 2026-08-19, before any SS read); the no-work exit leaves the
; bank untouched, the work path restores WALK after the workers.
; A/X/Y are dead at the hook point (render_subsector reloads them).
; ============================================================================
SEG_HIGH
; pseudocode:
;   pend = SSMASK[ss] & DIRTY            # dirty movers revealable via this ss
;   for m in 5..0 where pend has bit m:
;     ANIM_VAL = pos_hi(m)               # ANIM_WS[m*3+1], prescaled s8 height
;     anim_l0_worker (FHCH bytes + seg flags)
;     DIRTY &= ~bit(m)                   # applied == logical again
; --- scratch home $115B+ (2026-08-25): the anim scratch joins the
; objects block in the $1100 page — real RAM in BOTH builds (the
; scalar-state rule), runtime-written only (nothing to ship), and it
; buys the CODE region back ~24 bytes it no longer has. ---
anim_val2  = $0DDB                      ; pos>>7: the HALF-unit patch value
ah_pend2   = $0DDC
at_m       = $0DDD
at_t       = $0DDE
at_state   = $0DDF
at_timer   = $0DE0
at_fields  = $0DE1
at_wsteps  = $0DE2
at_c       = $0DE3
at_moved   = $0DE4                      ; was at_prevhi (the DIRTY rework
                                        ; retired the half-derive compare)
alw_nf     = $0DE5
alw_ng     = $0DE6
alw_nb     = $0DE7
alw_nv     = $0DE8
alw_y      = $0DE9
alw_hdr    = $0DEA                      ; 2 bytes
alw_fh     = $0DEC
alw_ch     = $0DED
alw_bfh    = $0DEE
alw_bch    = $0DEF
alw_f      = $0DF0
ai_t       = $0DF1
ai_midx    = $0DF2
anim_hub:
.scope
   LDX zp_node_ch_l
   LDA ANIM_SSMASK,X                       ; movers with segs in this subsector
   BEQ ah_done                             ; most visited ss are moverless: out
                                           ; before the DIRTY AND (measured -49
                                           ; MEAN on the anims-on corpus)
   AND ANIM_DIRTY
   BEQ ah_done
   STA ah_pend2
   LDX #5
ah_loop:
   LDA ah_pend2
   AND vc_bit_mask,X
   BEQ ah_next
   STX ANIM_CUR
; value = pos_hi of mover X (ws + X*3 + 1)
   TXA
   ASL A
   ADC ANIM_CUR                            ; A = X*3 (carry clear: X<=5)
   TAY
   LDA ANIM_WS+1,Y
   STA ANIM_VAL
   LDA ANIM_WS+0,Y                         ; anim_val2 = pos >> 7: the HALF-
   ASL A                                   ; unit patch value (back pairs +
   LDA ANIM_WS+1,Y                         ; jamb VEXPL bytes, 2026-08-25)
   ROL A
   STA anim_val2
   JSR anim_l0_worker                      ; heights + seg flags (pages itself)
; (the L2 VWH worker is gone: the private VWH slot bytes were write-only —
; the 6502 render projects from the header height bytes; VWH indices are Python-side
; cache keys. Stripped 2026-07-10.)
   LDX ANIM_CUR
   LDA ANIM_DIRTY
   EOR vc_bit_mask,X                       ; clear this mover's dirty bit
   STA ANIM_DIRTY
ah_next:
   DEX
   BPL ah_loop
   PAGE BANK_WALK                          ; the workers left SEG paged; the
                                        ; prologue's SS reads need WALK back
ah_done:
   JMP anim_ss_cont                        ; resume render_subsector
.endscope

; ============================================================================
; BANK_L0-context code: jump table (fixed entry addrs for the driver),
; per-frame tick, init, and the FHCH+flags patch worker.
; ============================================================================
SEG_HIGH

; (jt_anim_tick/jt_anim_init moved into the pinned MAIN jump table at
;  $2C1E/$2C21 — see bsp/header.s; the one-region merge lets ANIML2 float.)

; --- anim_tick: advance every mover's logical state; no table writes.
;     Per mover: Y = m*3 indexes the WS block, X = m*12 the CFG block.
;     Prescaled 8.8 arithmetic; bounds |int| <= ~30 so SBC-sign compares
;     are exact. Sets the mover's ANIM_DIRTY bit iff pos_hi changed. ---
; pseudocode (integerised Mover.tick, anim_sectors.py; FIELD-SCALED
; 2026-08-25 — speeds are world/FIELD by design, python's float side is
; world/SECOND real-dt: ticking once per variable-cost frame made door
; speed depend on scene cost AND ran waits ~4x their spec at a typical
; 4-field frame):
;   f = ANIM_FIELDS or 1                   # driver-written; harness = 1
;   wsteps = (TPRE + f) >> 2; TPRE = (TPRE + f) & 3
;   for m in 5..0:
;     state = WS[m*3+2] & $C0 ; timer = WS[m*3+2] & $3F
;     if state in (0 wait@A, 2 wait@B):
;       if timer:                          # 0 = hold forever (DR doors)
;         if timer > wsteps: timer -= wsteps
;         else: timer = 0; state += $40    # 0 -> 1 (A->B), 2 -> 3 (B->A)
;     elif state == 1 (A->B):
;       pos += speed88*f; if pos >= max88: pos = max88; state = 2; timer = wait_B
;     else (3, B->A):
;       pos -= speed88*f; if pos < min88:  pos = min88; state = 0; timer = wait_A
;     WS[m*3+2] = state | timer
;     if pos_hi != previous pos_hi: DIRTY |= bit(m)  # renderer bytes now stale
; (speed88*f = a bounded add-loop, f <= 32 by the pm_frame ABI cap; the
;  overshoot-then-clamp is the same final pos as f clamped single steps.)
anim_tick:
.scope
   LDA ANIM_ENABLE
   BNE at_on
   RTS
at_on:
   LDA ANIM_FIELDS                         ; driver-written field count;
   BNE at_f1                               ; 0 = no driver (py65 harness):
   LDA #1                                  ; tick as one field
at_f1:
   STA at_fields
   CLC
   ADC ANIM_TPRE                           ; accumulate fields into the
   TAX                                     ; prescaler; whole /4 steps are
   AND #3                                  ; this tick's wait budget, the
   STA ANIM_TPRE                           ; 0-3 residue carries over
   TXA                                     ; (TAX/TXA: X is dead until the
   LSR A                                   ;  mover loop reloads it)
   LSR A
   STA at_wsteps
   LDA #5
   STA at_m
at_loop:
   LDA at_m
   ASL A
   ADC at_m                                ; m*3 (no carry: m<=5)
   TAY
   ASL A                                   ; m*12 = (m*3)<<2 (<= 60, no
   ASL A                                   ; carry; TAY left A intact)
   TAX
   LDA ANIM_WS+2,Y
   AND #$3F
   STA at_timer
   LDA ANIM_WS+2,Y
   AND #$C0
   STA at_state
   BNE at_notwa
   JMP at_wait                             ; 0: wait at A
at_notwa:
   CMP #$80
   BNE at_notwb
   JMP at_wait                             ; 2: wait at B
at_notwb:
   CMP #$40
   BEQ at_up                               ; 1: A -> B
; --- 3: B -> A (pos -= speed, clamp at min = CFG+0) ---
; (The D_FWD gate that zeroed the forward-coherence class on travelling
; frames died 2026-09-03: it dated from the D cache that served whole
; has_gap verdicts.  Today's dbox_check stores only angle-derived state
; -- code 1 = angle cull, else the box's x-extent -- and runs has_gap
; LIVE on every serve, so mover heights never enter a cached byte.  The
; gate was costing the D class on ~half of all walking frames, since
; the lifts cycle perpetually.  FB-identity gate with anims ticking on
; both twins: dwalk_bench --anim.)
   INC at_moved                            ; travelling => DIRTY at at_done
   LDA at_fields
   STA at_c
at_dnlp:
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   DEC at_c
   BNE at_dnlp
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+0,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+1,X
   BPL at_jdone                            ; pos >= min: still travelling
                                        ; (rides the clamp tail's own JMP
                                        ; — at_done left branch range when
                                        ; the field loops landed 2026-08-25)
   LDA ANIM_CFG+0,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+1,X
   STA ANIM_WS+1,Y
   ZERO at_state
   LDA ANIM_CFG+6,X                        ; wait_at_A
   STA at_timer
at_jdone:
   JMP at_done

at_up:
; --- 1: A -> B (pos += speed, clamp at max = CFG+2) ---
   INC at_moved                            ; travelling => DIRTY at at_done
   LDA at_fields
   STA at_c
at_uplp:
   LDA ANIM_WS+0,Y
   CLC
   ADC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   ADC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   DEC at_c
   BNE at_uplp
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+2,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+3,X
   BMI at_done                             ; pos < max: still travelling
   LDA ANIM_CFG+2,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+3,X
   STA ANIM_WS+1,Y
   LDA #$80
   STA at_state
   LDA ANIM_CFG+7,X                        ; wait_at_B
   STA at_timer
   JMP at_done

at_wait:
   LDA at_timer                            ; wait 0 = HOLD FOREVER (DR doors
   BEQ at_done                             ; idle shut until pmove_use pokes
   SEC                                     ; the state; 2026-08-14)
   SBC at_wsteps                           ; consume this tick's 4-field
   BEQ at_expire                           ; steps in ONE subtract (multi-
   BCS at_hold                             ; step at heavy frames); > 0 with
                                        ; no borrow = still waiting
at_expire:
; wait expired (timer <= wsteps): 0 -> 1 (A->B), 2 -> 3 (B->A); timer
; stays 0 while moving — pack state|0 straight into WS and skip
; at_done's staging (a wait never raises at_moved)
   LDA at_state
   CLC
   ADC #$40
   STA ANIM_WS+2,Y
   JMP at_clean
at_hold:
   STA at_timer

at_done:
   LDA at_state
   ORA at_timer
   STA ANIM_WS+2,Y
; DIRTY = "a move arm ran": while travelling pos STRICTLY changes every
; tick (speed88 >= 1, arrival clamps from beyond), so the arms raise
; at_moved and the waiting majority pays one load+branch instead of two
; 16-cycle pos>>7 derives (2026-08-25 grind). A patch can repeat while
; pos>>7 sits inside one half step — same bytes rewritten, rare, cheap.
   LDA at_moved
   BEQ at_clean
   DEC at_moved                            ; exactly one INC per travelling
                                        ; tick (anim_init zeroes it), so
                                        ; DEC restores 0
   LDX at_m
   LDA ANIM_DIRTY
   ORA vc_bit_mask,X                       ; (shared 1<<n table, defq.s)
   STA ANIM_DIRTY
at_clean:
   DEC at_m
   BMI at_end
   JMP at_loop
at_end:
   RTS
.endscope


; --- anim_l0_worker: patch FHCH bytes + re-derive seg flags for mover
;     ANIM_CUR with value ANIM_VAL. ENTRY BANK-AGNOSTIC since 2026-08-19
;     (the hub is entered under WALK now): pages SEG itself for the TABL0
;     block walk and the header/BPAL patches, and flips to WALK around
;     every touch of the per-subsector front pages, which live in BANK B
;     with the rest of the SS planes. ---
; TABL0 block (gen_6502_tables): n_front, n_back, n_flag, n_vexpl, then
; n_front u16 FRONT-page addrs (bank B: SS_FH/SS_CH entries), n_back u16
; back-pair addrs (bank A: BPAL entries), then n_flag x (u16 seg-header
; flag addr, u16 FRONT-pair addr) covering every two-sided seg touching
; the sector; the BACK pair rides the flags address.
; The quad is SPLIT since 2026-08-17: fh/ch live on the per-subsector pages
; (ch is always fh + $100 — the pages abut) and bfh/bch in the header.
; pseudocode:
;   for each fhch addr: *addr = ANIM_VAL
;   for each flag entry:                       # packer's rules, post-patch
;     fh, ch = front[0], front[$100]
;     bfh, bch = BPAL_BFH[id], BPAL_BCH[id]   # id = the header's +SH_BPAL
;     f = *hdr & ~(SOLID|NEEDBT|NEEDBB)        # & $B3
;     if bch <= fh or bfh >= ch: f |= SOLID
;     else: if bch < ch: f |= NEEDBT ; if bfh > fh: f |= NEEDBB
;     *hdr = f
SEG_HIGH
anim_l0_worker:
.scope
   PAGE BANK_SEG                           ; TABL0 + headers + BPAL bank
   LDA ANIM_CUR
   ASL A
   TAY
   LDA ANIM_TABL0,Y
   STA zp_anim_p
   LDA ANIM_TABL0+1,Y
   STA zp_anim_p+1
   LDY #0
   LDA (zp_anim_p),Y                       ; n_front (bank-B SS-page addrs)
   STA alw_nf
   INY
   LDA (zp_anim_p),Y                       ; n_back (bank-A BPAL addrs)
   STA alw_nb
   INY
   LDA (zp_anim_p),Y                       ; n_flag
   STA alw_ng
   INY
   LDA (zp_anim_p),Y                       ; n_vexpl (jamb patch targets)
   STA alw_nv
   INY
; FRONT patches: the addr comes out of TABL0 under SEG, the byte lands in
; a bank-B SS page — flip per write (cold: <= 2 per mover)
alw_floop:
   LDA alw_nf
   BEQ alw_back
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   PAGE BANK_WALK
   LDA ANIM_VAL
   STA (zp_anim_w)                         ; non-indexed (the LDY died)
   PAGE BANK_SEG
   LDY alw_y
   DEC alw_nf
   JMP alw_floop
; BACK patches: BPAL entries, bank A — no flipping
alw_back:
   LDA alw_nb
   BEQ alw_flags
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   LDA anim_val2                           ; HALF units (mover BPAL pool)
   STA (zp_anim_w)
   LDY alw_y
   DEC alw_nb
   JMP alw_back
alw_flags:
; per flag entry: u16 hdr flag addr, u16 FHCH quad addr
   LDA alw_ng
   BNE alw_gbody
   JMP alw_done
alw_gbody:
; walk the entry's THREE addresses out of the block first (Y is the block
; cursor and must survive to alw_y — read every u16 before touching it)
   LDA (zp_anim_p),Y
   STA alw_hdr
   INY
   LDA (zp_anim_p),Y
   STA alw_hdr+1
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w                            ; FRONT pair: fh here, ch at +$100
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
; front pair off the per-subsector pages (fh, then ch one page up — the two
; pages abut by construction; BANK B since 2026-08-19, so flip around it)
   PAGE BANK_WALK
   LDY #0
   LDA (zp_anim_w),Y
   STA alw_fh
   INC zp_anim_w+1
   LDA (zp_anim_w),Y
   STA alw_ch
   PAGE BANK_SEG
; back pair via the PALETTE (2026-08-17): the id byte sits in the SAME header
; as the flags byte, so its address is derived rather than carried — TABL0's
; 252 B budget has no room for a third u16 per entry. Mover-touching segs hold
; PRIVATE palette entries, so patching one never moves a neighbour.
   LDA alw_hdr
   CLC
   ADC #LAY_SH_BPAL - LAY_SH_FLAGS
   STA zp_anim_w
   LDA alw_hdr+1
   ADC #0
   STA zp_anim_w+1
   LDA (zp_anim_w),Y                        ; Y still 0: the palette id
   TAX
   LDA ROM_BPAL_BFH_C,X
   STA alw_bfh
   LDA ROM_BPAL_BCH_C,X
   STA alw_bch
; HALF-UNIT tier: a mover-valued back pair (id bit 6) is in half units —
; double the front pair so the quad compares below are unit-consistent
; (the doubled range needs the V-corrections on the SBCs).
   TXA
   AND #$40
   BEQ alw_units_ok
   ASL alw_fh
   ASL alw_ch
alw_units_ok:
; flags = old & ~(SOLID|NEEDBT|NEEDBB) = old & ~$4C (SOLID=$40)
   LDA alw_hdr
   STA zp_anim_w
   LDA alw_hdr+1
   STA zp_anim_w+1
   LDA (zp_anim_w)                         ; non-indexed (Y untouched to the
   AND #$83                                ; ~(SOLID|NEEDBT|NEEDBB|STEPUP_T/B)
   STA alw_f
; SOLID iff bch <= fh  or  bfh >= ch   (plain SBC sign tests: the packer
; asserts every mover quad's doubled diffs stay inside s8 — see
; wad_packed's H2 bound assert)
   LDA alw_bch
   SEC
   SBC alw_fh
   BMI alw_solid
   BEQ alw_solid
   LDA alw_bfh
   SEC
   SBC alw_ch
   BPL alw_solid
; portal, top: NEEDBT iff bch < ch ; STEPUP_T iff bch > ch (baked
; verdicts — the cascade dispatches on them, 2026-08-13)
   LDA alw_bch
   SEC
   SBC alw_ch
   BEQ alw_nott                            ; equal: neither
   BMI alw_bt
   LDA alw_f
   ORA #$10                                ; SF_STEPUP_T
   BNE alw_stt                             ; (always: bit set)
alw_bt:
   LDA alw_f
   ORA #$04                                ; SF_NEEDBT
alw_stt:
   STA alw_f
alw_nott:
; portal, bottom: NEEDBB iff bfh > fh ; STEPUP_B iff bfh < fh
   LDA alw_fh
   SEC
   SBC alw_bfh
   BEQ alw_nobb                            ; equal: neither
   BMI alw_bb
   LDA alw_f
   ORA #$20                                ; SF_STEPUP_B
   BNE alw_stb                             ; (always: bit set)
alw_bb:
   LDA alw_f
   ORA #$08                                ; SF_NEEDBB
alw_stb:
   STA alw_f
alw_nobb:
   JMP alw_wf
alw_solid:
   LDA alw_f
   ORA #$40                                ; SF_SOLID
   STA alw_f
alw_wf:
   LDA alw_f                               ; NEEDED: the BPL alw_nobb path
   STA (zp_anim_w)                         ; arrives with the SBC result in A
                                           ; (regscan false positive 2026-07-19
                                           ; — its meet missed the mid-chain
                                           ; branch; anim6502 caught it)
   LDY alw_y
   DEC alw_ng
   JMP alw_flags
alw_done:
; jamb VEXPL patches: u16 addrs of the entry byte holding the MOVING
; bound of an in-plane door/lift jamb span (VEXPL_LO or VEXPL_HI slot;
; gen_6502_tables). Value = ANIM_VAL, same as the FHCH patches. The
; targets live in BANK_C banked (VEXPL $A100/$A180) while the list is
; read from TABL0 under BANK_SEG — so each address is fetched first,
; then the write runs under a C excursion.
alw_vexpl:
   LDA alw_nv
   BEQ alw_ret
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   PAGE BANK_C
   LDA ANIM_VAL                            ; INTEGER units (VEXPL stays the
   STA (zp_anim_w)                         ; integer tier this pass — see
   PAGE BANK_SEG
   LDY alw_y
   DEC alw_nv
   JMP alw_vexpl
alw_ret:
   RTS
.endscope

; ============================================================================
; sqr_fill — regenerate the quarter-square quad+mirrors at $0200-$07FF.
; The quad lives on OS-owned pages (vector page + workspace) that no disc
; file can load, and never needs loading: f(n) = n*n >> 2 falls out of the
; recurrence f(n+1) = f(n) + ((n+1) >> 1). 1,024 bytes in ~13k cycles,
; once per boot. Callers: anim_init (walk_drv and the tube driver both
; come through it) and banked_boot's DRV directly (ENG_SQR_FILL).
; The harnesses poke identical values; bare-boot's FB compare against the
; poked model is the exactness gate. Clobbers A, X, Y, zp_anim_w pair.
; (The COLPORT copy-down used to live in this slot: the ports ship at
; $1A00 now, inside LOW / the tube CODE file. Do not resurrect $A900
; staging — it overlays the psi planes.)
; ============================================================================
SEG_HIGH
sqr_fill:
.scope
   LDA #0
   STA zp_anim_w                           ; f16 = 0
   STA zp_anim_w+1
   TAX                                     ; n = 0
   TAY                                     ; delta = 0
sq1:
   LDA zp_anim_w
   STA SQR_LO,X                            ; f(n) lo
   LDA zp_anim_w+1
   STA SQR_HI,X                            ; f(n) hi
   TXA
   LSR A
   BCC sq1e                                ; leaving odd n: delta+1
   INY                                     ;  (delta = (n+1) >> 1)
sq1e:
   TYA
   CLC
   ADC zp_anim_w
   STA zp_anim_w
   BCC sq1c
   INC zp_anim_w+1
sq1c:
   INX
   BNE sq1
sq2:                                       ; n = 256 + X (parity = X parity)
   LDA zp_anim_w
   STA SQR2_LO,X
   LDA zp_anim_w+1
   STA SQR2_HI,X
   TXA
   LSR A
   BCC sq2e
   INY
sq2e:
   TYA
   CLC
   ADC zp_anim_w
   STA zp_anim_w
   BCC sq2c
   INC zp_anim_w+1
sq2c:
   INX
   BNE sq2
; mirror tail (2026-09-01): the even-mirror pages below each plane —
; MIR[k] = f(256-k), MIR[0] = f(256) — so a diff-side base+mag walk
; serves any M in 0..256. ~6.4k boot cycles.
   LDX #1
   LDY #$FF
sqm:
   LDA SQR_LO,X
   STA SQR_MIR_LO,Y
   LDA SQR_HI,X
   STA SQR_MIR_HI,Y
   INX
   DEY
   BNE sqm
   LDA #0
   STA SQR_MIR_LO                          ; f(256) = 16384: lo 0
   LDA #64
   STA SQR_MIR_HI                          ; hi 64
   RTS
.endscope

; sqr_fill_cold — the fill + pmove displacement-cache cold-init. The
; cache scratch overlays boot-time code bytes, and a garbage key match
; would serve a garbage displacement; pmc_fld = 0 can never match
; (fields are 1..10). Lives in PMB4 (past the CODE tail) so the 5 bytes
; don't shift the render code behind anim.s. Every boot path runs it:
; anim_init JSRs it, and ENG_SQR_FILL (the bare-boot driver's fill hook)
; resolves HERE (asmbuild engine-syms alias).
SEG_PMB4
.global pmt_blk
sqr_fill_cold:
; zero the pm survivor-replay block (pmt_blk, LINKER-allocated since
; 2026-09-02): engine-owned state that used to ship as LOW-tail zeros;
; junk-RAM boots must not leak into pmt_ok-class cold-init assumptions
   LDX #12
   LDA #0
sqc_pmz:
   STA pmt_blk,X
   DEX
   BPL sqc_pmz
   JSR sqr_fill
   LDA #0
   STA pmc_fld
   STA pmt_ok                           ; empty-columns certificate too
   STA pm_okf                           ; force the raw re-derive on the
   STA pm_lmv                           ;  first frame + no fast commit
   RTS                                  ;  until a real zonly classifies

; --- anim_init: load start state from CFG, mark all dirty, enable, and
;     point the subsector hook at the hub. Runs with BANK_L2 paged. ---
;   in : ANIM_CFG (+8 start88, +10 packed start state/timer)
;   out: ANIM_WS seeded (all 6 movers), ANIM_DIRTY = $3F (every mover patches
;        on first visibility, even before any motion), ANIM_ENABLE = 1,
;        anim_ss_hook operand SMC-patched -> anim_hub, ANIM_SSMASK copied
;        down from its L2 staging page (banked only — see below).
SEG_HIGH
anim_init:
.scope
; sqr fill first — the COLD arm (quad + pm cache init, PMB4): a JSR so
; the one-frame bare-boot driver (banked_boot DRV), which never touches
; anims OR movement, can still call the plain fill via ENG_SQR_FILL.
   JSR sqr_fill_cold
   JSR obj_anyb_fill                       ; OBJ_BITS -> main (objects.s)
; (SSMASK copy-down DELETED 2026-08-19: the hub reads the shipped page
; in place — banked $B400 under the WALK bank it is entered with, flat
; $E500. The whole failure class the copy carried — the 355c126 frozen
; doors, the $B4DD tail drag, the COLIDX-in-the-tail scar — dies with
; it; jsbeeb anim_live remains the catcher for shipped-mask breakage.)
   LDA #5
   STA ai_midx
ai_m:
   LDA ai_midx
   ASL A
   CLC
   ADC ai_midx
   TAY                                     ; m*3
   ASL A                                   ; m*12 = (m*3)<<2 (TAY leaves
   ASL A                                   ; A intact; <= 60, no carry)
   TAX
   LDA ANIM_CFG+8,X                        ; start pos (8.8 prescaled)
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+9,X
   STA ANIM_WS+1,Y
   LDA ANIM_CFG+10,X                       ; packed start state/timer
   STA ANIM_WS+2,Y
   DEC ai_midx
   BPL ai_m
   LDA #$3F
   STA ANIM_DIRTY
   ZERO at_moved                           ; $11xx ships nothing: boot garbage
                                        ; here would only cost one spurious
                                        ; repatch, but determinism is free
   LDA #1
   STA ANIM_ENABLE
   LDA #<anim_hub
   STA anim_ss_hook+1
   LDA #>anim_hub
   STA anim_ss_hook+2
   RTS
.endscope


SEG_CODE
