; GENERATED by master_assets.py (step 7n) -- do not edit.
; The flats' far tone: FAR_DM, the least D per line pair, and the
; tone byte per flat (bank 6 code area).
	.segment "MB6C"
far_dm:				; FAR_T = 4
	.byte 1,1,1,2,2,3,3,4,5,6,7,7,8,9,10,11
	.byte 12,13,15,16,17,18,19,21,22,23,25,26,27,29,30,32
	.byte 33,35
far_tone:			; per flat id
	.byte $10,$00,$01,$10,$10,$10,$14,$01,$10,$10,$01,$01,$10,$01,$14,$C6
	.byte $11,$01,$01,$00,$01
