#!/usr/bin/env python3
"""Build the Master engine disc (step 1, docs/master_textured_spec.md).

    python3 tools/build_master_ssd.py      -> build/master/doom_master.ssd

The MASTER engine link (asmbuild variant 2) running the Model B walk driver
with its MASTER arms: 256x160 shadow Mode 1, both buffers in shadow RAM,
frame-time HUD, and since step 3 the span-diff filler drawing every frame
in solid shades (src/master/mfill.s).

Files on the disc (DFS, boot option *RUN):
  !BOOT   loader, $1900 (src/master/mboot.s)
  MBANK4  bank A image (seg headers, verts, recips, ...)  staged $3000
  MBANK7  bank B image (nodes, bbox, collision, anim), the
          music stream at $A600                           staged $3000
  MBANK5  wall textures; the music player at $B800        staged $3000
  MBANK6  wall textures, flats, the mb6 part records      staged $3000
  MMAIN   engine MAIN $0F00-$57FF (driver + code)         loads in place
  MCBITS  bank-C content laid linear, $5800-$79FF, and
          the mtex_ix column index blob to $7FFF          loads in place
  MHAZEL  HAZEL: pattern, HUD, FLIP, font at $C000; the filler +
          wall texturer and its sky map at $C800          staged $3000
  MANDY   ANDY: the per-seg wall tables (master_walls)    staged $3000
  MPANEL  the control panel (master_panel): the bottom    staged $3000
          24 lines under both buffers, shadow $5800
  MGUN    gun_b0, the buffer-0 gun overlay, shadow $3000  staged $3000
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
os.environ.setdefault('SDL_VIDEODRIVER', 'dummy')
os.environ.setdefault('PYGAME_HIDE_SUPPORT_PROMPT', '1')

import master_assets as M
import master_panel
import abi
from build_master_display import ssd, COLBYTE   # same band pattern

SRC = os.path.join(ROOT, 'src', 'master')
OUT = os.path.join(ROOT, 'build', 'master')
HOST = 0xFF0000                                    # DFS host-address bits

# 3x5 hex digits in a 4x8 cell, white (logical 3) on black
DIGITS = ['111101101101111', '010110010010111', '111001111100111', '111001111001111',
          '101101111001001', '111100111001111', '111100111101111', '111001001001001',
          '111101111101111', '111101111001111', '111101111101101', '110101110101110',
          '111100100100111', '110101101101110', '111100111100111', '111100111100100']


def font():
    """16 bytes per digit (Mode 2, step 6a): a 4-pixel cell is two byte
    columns, its left column's 8 lines then its right's; the 3 x 5 glyph
    white (7) on black, lines 2..6."""
    out = []
    for d in DIGITS:
        rows = [d[i:i + 3] + '0' for i in range(0, 15, 3)]
        cell = ['0000', '0000'] + rows + ['0000']                # 8 lines
        for half in (0, 1):
            out += [M.mode2_byte(tuple(7 * int(b) for b in r[2 * half:2 * half + 2]))
                    for r in cell]
    return out


def hazel_tables():
    def rows(name, data):
        return [f'{name}:'] + ['\t.byte ' + ','.join(f'${v:02X}' for v in data[i:i + 16])
                               for i in range(0, len(data), 16)]
    s = ['; GENERATED by tools/build_master_ssd.py -- do not edit.']
    s += rows('colbyte', COLBYTE) + rows('font', font())
    open(os.path.join(OUT, 'mhazel_tab.s'), 'w').write('\n'.join(s) + '\n')
    open(os.path.join(OUT, 'mhazel_tab.inc'), 'w').write('; GENERATED\n')


def asm(name, defs=()):
    obj, binp = os.path.join(OUT, f'{name}.o'), os.path.join(OUT, f'{name}.bin')
    cmd = ['ca65', '--cpu', '65C02', '-D', 'BANKED=1', '-D', 'MASTER=1',
           '-I', OUT, '-I', SRC, '-I', os.path.join(ROOT, 'src')]
    for d in defs:
        cmd += ['-D', d]
    subprocess.run(cmd + [os.path.join(SRC, f'{name}.s'), '-o', obj], check=True)
    subprocess.run(['ld65', '-C', os.path.join(SRC, f'{name}.cfg'), obj, '-o', binp,
                    '-Ln', os.path.join(OUT, f'{name}.lab')], check=True)
    return open(binp, 'rb').read()


def engine_images():
    import pygame
    pygame.init()
    import e1m1 as dw
    from banked_bsp import MasterBspRender
    r = MasterBspRender(dw.packed_layout, dw.packed_rom_main, dw.packed_rom_detail,
                        dw.packed_bbox_table, dw.MAP_CENTER_X, dw.MAP_CENTER_Y, dw.PRESCALE)
    bm = r.bm
    import master_walls
    ti = master_walls.rig_images()
    bm.select(5)                                    # (writes back a cached window)
    b4 = bytes(bm._banks[abi.BANK_SEG])
    b7 = bytes(bm._banks[abi.BANK_WALK])
    main = bytes(bm[abi.LOW_BASE:abi.CBITS_M])
    cbits = bytes(bm[abi.CBITS_M:0x8000])           # code + C data + VPTAB + mtex_ix
    assert cbits[ti['ix_base'] - abi.CBITS_M:][:len(ti['ix'])] == ti['ix']
    hzeng = bytes(bm[0xC800:0xDE00])                # the filler + texturers + sky map
    b6 = bytes(bm._banks[abi.BANK_C])               # texels, flats, the fill's
                                                    # cold code, the mb6 tables
    return b4, b7, ti['b5'], b6, ti['andy'], main, cbits, hzeng


def music(b5, b7):
    """The music (step 7ac, master_music.py): the resident player into bank
    5 at MUS_STAGE (the boot stub copies it to MUS_ORG), the tune stream
    into bank 7 at MUS_STREAM; both regions must be empty."""
    import master_music
    res, stream, _, _ = master_music.build()

    def put(img, at, data, what):
        o = at - 0x8000
        assert not any(img[o:o + len(data)]), f'{what}: ${at:04X} is not free'
        return img[:o] + data + img[o + len(data):]
    return (put(b5, abi.MUS_STAGE, res, 'music player'),
            put(b7, abi.MUS_STREAM, stream, 'music stream'))


def build(tube=False):
    """The Master disc, or (tube) the Tube Master's (docs/tube_master.md H4):
    the TUBE engine link (its fill a request to the second processor, its
    host drawer in HAZEL) and SERVER, the fill server's image, which !BOOT
    loads into the second processor and starts. DOOM_ASMDEFS must already
    say TUBE=1 for it (__main__ sets it)."""
    os.makedirs(OUT, exist_ok=True)
    hazel_tables()
    b4, b7, b5, b6, andy, main, cbits, hzeng = engine_images()
    b5, b7 = music(b5, b7)
    hz = asm('mhazel')
    assert len(hz) <= 0x280, 'boot HAZEL block runs into the plane caches at $C280'
    hz = hz.ljust(0x800, b'\0') + hzeng            # $C000 pattern/HUD | $C800 filler
    assert len(andy) == 0x1000
    defs = [f'HAZEL_PAGES={(len(hz) + 255) // 256}']
    server = []
    if tube:
        import tube_req
        import tube_server
        load, img, entry = tube_server.Server(tube_req.ReqRef()).image()
        server = [('SERVER', load, entry, img)]     # (no HOST bits: the parasite)
        defs += ['TUBE=1', f'SERVER_ENTRY=${entry:04X}']
    boot = asm('mboot', defs)
    assert len(main) == 0x4900 and len(cbits) == 0x2800
    gun = open(os.path.join(ROOT, 'engine_gun_m.bin'), 'rb').read()   # gun_b0
    assert len(gun) <= 0x600, 'gun_b0 overruns shadow $3000-$35FF'
    files = [('!BOOT', HOST | 0x1900, HOST | 0x1900, boot),
             ('MBANK4', HOST | 0x3000, HOST | 0x3000, b4),
             ('MBANK7', HOST | 0x3000, HOST | 0x3000, b7),
             ('MBANK5', HOST | 0x3000, HOST | 0x3000, b5),
             ('MBANK6', HOST | 0x3000, HOST | 0x3000, b6),
             ('MMAIN', HOST | abi.LOW_BASE, HOST | abi.LOW_BASE, main),
             ('MCBITS', HOST | abi.CBITS_M, HOST | abi.CBITS_M, cbits),
             ('MHAZEL', HOST | 0x3000, HOST | 0x3000, hz),
             ('MANDY', HOST | 0x3000, HOST | 0x3000, andy),
             ('MPANEL', HOST | 0x3000, HOST | 0x3000, master_panel.panel_bytes()),
             ('MGUN', HOST | 0x3000, HOST | 0x3000, gun)] + server
    path = os.path.join(OUT, 'doom_tube.ssd' if tube else 'doom_master.ssd')
    ssd(files, path)
    for n, l, e, d in files:
        print(f'  {n:7s} &{l & 0xFFFF:04X}  {len(d):>6} B')
    print(f'wrote {os.path.relpath(path, ROOT)}')


if __name__ == '__main__':
    sys.path.insert(0, os.path.join(ROOT, 'tools'))
    tube = '--tube' in sys.argv
    os.environ['DOOM_ASMDEFS'] = 'TUBE=1' if tube else ''
    build(tube)
