#!/usr/bin/env python3
"""Build the Master engine disc (step 1, docs/master_textured_spec.md).

    python3 tools/build_master_ssd.py      -> build/master/doom_master.ssd

The MASTER engine link (asmbuild variant 2) running the Model B walk driver
with its MASTER arms: 256x160 shadow Mode 1, both buffers in shadow RAM,
frame-time HUD, and since step 3 the span-diff filler drawing every frame
in solid shades (src/master/mfill.s).

Files on the disc (DFS, boot option *RUN):
  !BOOT   loader, $1900 (src/master/mboot.s)
  MBANK4  bank A image (seg headers, verts, recips, ...)  staged $3000
  MBANK7  bank B image (nodes, bbox, collision, anim)     staged $3000
  MMAIN   engine MAIN $0F00-$57FF (driver + code)         loads in place
  MCBITS  bank-C content laid linear, $5800-$79FF         loads in place
  MHAZEL  HAZEL: pattern, HUD, FLIP, font at $C000; the step-3 filler
          and its sky map at $C800                        staged $3000
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
os.environ.setdefault('SDL_VIDEODRIVER', 'dummy')
os.environ.setdefault('PYGAME_HIDE_SUPPORT_PROMPT', '1')
os.environ['DOOM_CPU'] = '65c02'

import master_assets as M
import abi
from build_master_display import ssd, COLBYTE      # same band pattern

SRC = os.path.join(ROOT, 'src', 'master')
OUT = os.path.join(ROOT, 'build', 'master')
HOST = 0xFF0000                                    # DFS host-address bits

# 3x5 hex digits in a 4x8 cell, white (logical 3) on black
DIGITS = ['111101101101111', '010110010010111', '111001111100111', '111001111001111',
          '101101111001001', '111100111001111', '111100111101111', '111001001001001',
          '111101111101111', '111101111001111', '111101111101101', '110101110101110',
          '111100100100111', '110101101101110', '111100111100111', '111100111100100']


def font():
    out = []
    for d in DIGITS:
        rows = [d[i:i + 3] for i in range(0, 15, 3)]
        cell = [0, 0] + [int(r + '0', 2) for r in rows] + [0]     # 8 lines
        out += [(p << 4) | p for p in cell]       # colour 3 in both bit planes
    return out


def hazel_tables():
    def rows(name, data):
        return [f'{name}:'] + ['\t.byte ' + ','.join(f'${v:02X}' for v in data[i:i + 16])
                               for i in range(0, len(data), 16)]
    s = ['; GENERATED by tools/build_master_ssd.py -- do not edit.']
    s += rows('flip', M.FLIP) + rows('colbyte', COLBYTE) + rows('font', font())
    open(os.path.join(OUT, 'mhazel_tab.s'), 'w').write('\n'.join(s) + '\n')
    open(os.path.join(OUT, 'mhazel_tab.inc'), 'w').write('; GENERATED\n')


def asm(name, defs=()):
    obj, binp = os.path.join(OUT, f'{name}.o'), os.path.join(OUT, f'{name}.bin')
    cmd = ['ca65', '--cpu', '65C02', '-D', 'BANKED=1', '-D', 'MASTER=1',
           '-I', OUT, '-I', SRC, '-I', os.path.join(ROOT, 'src')]
    for d in defs:
        cmd += ['-D', d]
    subprocess.run(cmd + [os.path.join(SRC, f'{name}.s'), '-o', obj], check=True)
    subprocess.run(['ld65', '-C', os.path.join(SRC, f'{name}.cfg'), obj, '-o', binp,
                    '-Ln', os.path.join(OUT, f'{name}.lab')], check=True)
    return open(binp, 'rb').read()


def engine_images():
    import pygame
    pygame.init()
    import doom_wireframe as dw
    from banked_bsp import MasterBspRender
    r = MasterBspRender(dw.packed_layout, dw.packed_rom_main, dw.packed_rom_detail,
                        dw.packed_bbox_table, dw.MAP_CENTER_X, dw.MAP_CENTER_Y, dw.PRESCALE)
    bm = r.bm
    b4 = bytes(bm._banks[abi.BANK_SEG])
    b7 = bytes(bm._banks[abi.BANK_WALK])
    main = bytes(bm[abi.LOW_BASE:abi.CBITS_M])
    cbits = bytes(bm[abi.CBITS_M:0x7A00])           # code + C data + VPTAB
    hzeng = bytes(bm[0xC800:0xD000])                # the filler + its sky map
    return b4, b7, main, cbits, hzeng


def build():
    os.makedirs(OUT, exist_ok=True)
    hazel_tables()
    b4, b7, main, cbits, hzeng = engine_images()
    hz = asm('mhazel')
    assert len(hz) <= 0x800, 'boot HAZEL block runs into the filler at $C800'
    hz = hz.ljust(0x800, b'\0') + hzeng            # $C000 pattern/HUD | $C800 filler
    boot = asm('mboot', (f'HAZEL_PAGES={(len(hz) + 255) // 256}',))
    assert len(main) == 0x4900 and len(cbits) == 0x2200
    files = [('!BOOT', HOST | 0x1900, HOST | 0x1900, boot),
             ('MBANK4', HOST | 0x3000, HOST | 0x3000, b4),
             ('MBANK7', HOST | 0x3000, HOST | 0x3000, b7),
             ('MMAIN', HOST | abi.LOW_BASE, HOST | abi.LOW_BASE, main),
             ('MCBITS', HOST | abi.CBITS_M, HOST | abi.CBITS_M, cbits),
             ('MHAZEL', HOST | 0x3000, HOST | 0x3000, hz)]
    path = os.path.join(OUT, 'doom_master.ssd')
    ssd(files, path)
    for n, l, e, d in files:
        print(f'  {n:7s} &{l & 0xFFFF:04X}  {len(d):>6} B')
    print(f'wrote {os.path.relpath(path, ROOT)}')


if __name__ == '__main__':
    sys.path.insert(0, os.path.join(ROOT, 'tools'))
    build()
