#!/usr/bin/env python3
"""Build the Master display bring-up disc (step 1, docs/master_textured_spec.md).

    python3 tools/build_master_display.py   -> build/master/mdisplay.ssd

Generates the HAZEL tables (FLIP from master_assets, one combined wall byte
per byte column for buffer A, one floor byte per texel row for buffer B),
assembles src/master/mdisplay.s for the 65C02, and writes a single-file DFS
disc whose !BOOT is the program (load/exec &1900, boot option *RUN).
Also writes mdisplay_expect.bin: the exact 20K the two shadow buffers must
hold, for tools/master_rig.mjs to compare against.
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import master_assets as M

SRC = os.path.join(ROOT, 'src', 'master')
OUT = os.path.join(ROOT, 'build', 'master')
ORG = 0x1900
LUMA = (M.SHADE_RGB @ M.LUMA)
ORDER = sorted(range(len(M.SHADES)), key=lambda s: LUMA[s])   # dark -> light
N = len(ORDER)                          # Mode 2 (step 6a): the 8 colours
FLIP = bytes(range(256))                # (Mode 2: no cross-hatch -- identity)


def wall_pair(x):
    """Combined byte for byte column x: strips 2x, 2x+1 in N bands."""
    sa, sb = (ORDER[s * N // 128] for s in (2 * x, 2 * x + 1))
    return M.wall_pair(M.wall_byte(sa), M.wall_byte(sb))


COLBYTE = [wall_pair(x) for x in range(64)]
ROWBYTE = [M.floor_byte(ORDER[r * N // 80]) for r in range(80)]


def buffers():
    """The two 10K buffers exactly as the 6502 must draw them."""
    a, b = bytearray(10240), bytearray(10240)
    for y in range(160):
        for x in range(64):
            off = (y >> 3) * 512 + x * 8 + (y & 7)
            ca, rb = COLBYTE[x], ROWBYTE[y >> 1]
            a[off] = ca if y % 2 == 0 else FLIP[ca]
            b[off] = rb if y % 2 == 0 else FLIP[rb]
    return bytes(a + b)


def tables():
    def rows(name, data):
        return [f'{name}:'] + ['\t.byte ' + ','.join(f'${v:02X}' for v in data[i:i + 16])
                               for i in range(0, len(data), 16)]
    s = ['; GENERATED by tools/build_master_display.py -- do not edit.',
         '\t.align 256'] + rows('flip', FLIP) + rows('colbyte', COLBYTE) + rows('rowbyte', ROWBYTE)
    open(os.path.join(OUT, 'mdisplay_tab.s'), 'w').write('\n'.join(s) + '\n')
    open(os.path.join(OUT, 'mdisplay_tab.inc'), 'w').write(
        '; GENERATED by tools/build_master_display.py\nCOLS = 64\nTEXROWS = 80\n')


def ssd(files, path):
    """Minimal single-sided 80-track DFS image; boot option 2 (*RUN !BOOT)."""
    disc = bytearray(800 * 256)
    disc[0:8] = b'MDOOM\x00\x00\x00'
    disc[256 + 5] = len(files) * 8
    nxt = 2
    for i, (name, load, exe, data) in enumerate(files):
        off, m = 8 + 8 * i, 256 + 8 + 8 * i
        disc[off:off + 7] = name.encode().ljust(7)[:7]
        disc[off + 7] = ord('$')
        disc[m:m + 6] = bytes((load & 255, load >> 8 & 255, exe & 255, exe >> 8 & 255,
                               len(data) & 255, len(data) >> 8 & 255))
        disc[m + 6] = ((nxt >> 8 & 3) | (len(data) >> 16 & 3) << 4      # load / exe bits 16-17:
                       | (load >> 16 & 3) << 2 | (exe >> 16 & 3) << 6)  #  &FFxxxx (3) is the host
        disc[m + 7] = nxt & 255
        disc[nxt * 256:nxt * 256 + len(data)] = data
        nxt += (len(data) + 255) // 256
    disc[256 + 6] = (2 << 4) | (800 >> 8)
    disc[256 + 7] = 800 & 255
    open(path, 'wb').write(disc)


def build():
    os.makedirs(OUT, exist_ok=True)
    tables()
    obj, binp, lab = (os.path.join(OUT, n) for n in ('mdisplay.o', 'mdisplay.bin', 'mdisplay.lab'))
    subprocess.run(['ca65', '--cpu', '65C02', '-D', 'BANKED=1', '-D', 'MASTER=1',
                    '-I', OUT, '-I', SRC, '-I', os.path.join(ROOT, 'src'),
                    os.path.join(SRC, 'mdisplay.s'), '-o', obj], check=True)
    subprocess.run(['ld65', '-C', os.path.join(SRC, 'mdisplay.cfg'), obj, '-o', binp,
                    '-Ln', lab], check=True)
    prog = open(binp, 'rb').read()
    ssd([('!BOOT', 0xFF0000 | ORG, 0xFF0000 | ORG, prog)], os.path.join(OUT, 'mdisplay.ssd'))
    open(os.path.join(OUT, 'mdisplay_expect.bin'), 'wb').write(buffers())
    print(f'mdisplay.ssd: !BOOT {len(prog)} B at &{ORG:04X}')


if __name__ == '__main__':
    build()
